### ISSUE TITLE
Provide help boxes

### ISSUE THREAD

**Issue by adam3smith** [adam3smith/AnnoREP-Frontend#20]
## Use Case

I a user doesn't understand a step, there should be an easily accessible explanation right at that spot

## Solution

Some sort of small pop-up, maybe with a question mark icon would be great. Content, again, can come from us.

**Comment by tohuynh** [comment]
![image](https://user-images.githubusercontent.com/37560480/136288503-51c20c56-ade5-4b99-bb8c-2db93d5b7577.png)

@nniiicc @dkgeorgetown What additional text/message could be added to the two input fields that would help users retrieve their API tokens and login to AnnoRep?

**Comment by nniiicc** [comment]
Instead of the last few sentences - lets just try "Don't have an API token? Use the links below to generate an API token."
